import type { CatalogProductCard } from "./types";

type CatalogCategorySeed = {
  id: string;
  name: string;
  slug: string;
  description: string;
  seoTitle?: string;
  seoDescription?: string;
};

type CatalogProductSeed = CatalogProductCard & {
  featuredRank: number;
  newestRank: number;
};

export const catalogCategorySeeds: CatalogCategorySeed[] = [
  {
    id: "category-home-care",
    name: "Home Care",
    slug: "home-care",
    description: "Cleaning, laundry, and restock-friendly home essentials.",
    seoTitle: "Home Care Essentials",
    seoDescription: "Shop Karachi-ready home care products with simple filtering and clean category URLs.",
  },
  {
    id: "category-grocery",
    name: "Grocery",
    slug: "grocery",
    description: "Pantry staples, snacks, and quick household top-ups.",
    seoTitle: "Grocery Staples",
    seoDescription: "Browse pantry and grocery essentials with simple price, stock, and discount filters.",
  },
  {
    id: "category-personal-care",
    name: "Personal Care",
    slug: "personal-care",
    description: "Daily-use hygiene, skincare, and wellness basics.",
    seoTitle: "Personal Care Picks",
    seoDescription: "Explore personal care products through scalable category listing scaffolds.",
  },
];

export const catalogProductSeeds: CatalogProductSeed[] = [
  {
    id: "product-ultra-wash",
    slug: "ultra-wash-detergent-1kg",
    name: "Ultra Wash Detergent 1kg",
    description: "Strong stain removal for everyday laundry loads.",
    categorySlug: "home-care",
    price: 899,
    compareAt: 1099,
    inventoryQuantity: 18,
    averageRating: 4.7,
    reviewCount: 32,
    imageLabel: "Laundry care",
    imageTone: "sky",
    attributeSummary: ["Powder", "1kg"],
    featuredRank: 1,
    newestRank: 4,
  },
  {
    id: "product-floor-cleaner",
    slug: "citrus-floor-cleaner-900ml",
    name: "Citrus Floor Cleaner 900ml",
    description: "Fresh-scent floor cleaner for daily mopping.",
    categorySlug: "home-care",
    price: 499,
    compareAt: 649,
    inventoryQuantity: 4,
    averageRating: 4.2,
    reviewCount: 11,
    imageLabel: "Floor cleaner",
    imageTone: "emerald",
    attributeSummary: ["Citrus", "900ml"],
    featuredRank: 2,
    newestRank: 6,
  },
  {
    id: "product-trash-bags",
    slug: "drawstring-trash-bags-30-pack",
    name: "Drawstring Trash Bags 30 Pack",
    description: "Leak-resistant bags for kitchen and utility use.",
    categorySlug: "home-care",
    price: 349,
    inventoryQuantity: 0,
    averageRating: 3.9,
    reviewCount: 8,
    imageLabel: "Trash bags",
    imageTone: "slate",
    attributeSummary: ["30 bags", "Medium"],
    featuredRank: 3,
    newestRank: 8,
  },
  {
    id: "product-olive-blend",
    slug: "olive-blend-cooking-oil-1l",
    name: "Olive Blend Cooking Oil 1L",
    description: "Daily-use blend for frying, sauteing, and salad prep.",
    categorySlug: "grocery",
    price: 1299,
    compareAt: 1499,
    inventoryQuantity: 9,
    averageRating: 4.8,
    reviewCount: 45,
    imageLabel: "Cooking oil",
    imageTone: "amber",
    attributeSummary: ["1L", "Bottle"],
    featuredRank: 4,
    newestRank: 2,
  },
  {
    id: "product-basmati-rice",
    slug: "premium-basmati-rice-5kg",
    name: "Premium Basmati Rice 5kg",
    description: "Long-grain rice for family meals and weekend hosting.",
    categorySlug: "grocery",
    price: 2099,
    compareAt: 2499,
    inventoryQuantity: 12,
    averageRating: 4.6,
    reviewCount: 27,
    imageLabel: "Rice pack",
    imageTone: "rose",
    attributeSummary: ["5kg", "Family pack"],
    featuredRank: 5,
    newestRank: 1,
  },
  {
    id: "product-tea-bags",
    slug: "strong-brew-tea-bags-100-pack",
    name: "Strong Brew Tea Bags 100 Pack",
    description: "Daily chai essential with a strong, balanced flavor.",
    categorySlug: "grocery",
    price: 599,
    inventoryQuantity: 3,
    averageRating: 4.1,
    reviewCount: 14,
    imageLabel: "Tea bags",
    imageTone: "sky",
    attributeSummary: ["100 tea bags", "Black tea"],
    featuredRank: 6,
    newestRank: 5,
  },
  {
    id: "product-face-wash",
    slug: "hydra-care-face-wash",
    name: "Hydra Care Face Wash",
    description: "Gentle daily cleanser made for repeat use.",
    categorySlug: "personal-care",
    price: 699,
    inventoryQuantity: 22,
    averageRating: 4.5,
    reviewCount: 19,
    imageLabel: "Face wash",
    imageTone: "emerald",
    attributeSummary: ["100ml", "Daily care"],
    featuredRank: 7,
    newestRank: 3,
  },
  {
    id: "product-body-lotion",
    slug: "silk-soft-body-lotion-250ml",
    name: "Silk Soft Body Lotion 250ml",
    description: "Lightweight hydration for dry and normal skin.",
    categorySlug: "personal-care",
    price: 849,
    compareAt: 999,
    inventoryQuantity: 5,
    averageRating: 4.3,
    reviewCount: 16,
    imageLabel: "Body lotion",
    imageTone: "rose",
    attributeSummary: ["250ml", "Moisturizing"],
    featuredRank: 8,
    newestRank: 7,
  },
  {
    id: "product-toothpaste",
    slug: "fresh-mint-toothpaste-120g",
    name: "Fresh Mint Toothpaste 120g",
    description: "Everyday oral care with a clean mint finish.",
    categorySlug: "personal-care",
    price: 279,
    compareAt: 349,
    inventoryQuantity: 14,
    averageRating: 4.0,
    reviewCount: 9,
    imageLabel: "Toothpaste",
    imageTone: "slate",
    attributeSummary: ["120g", "Mint"],
    featuredRank: 9,
    newestRank: 9,
  },
];
